package com.quotes.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF895100)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFffdcb8)
val md_theme_light_onPrimaryContainer = Color(0xFF2c1700)
val md_theme_light_secondary = Color(0xFF666000)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFf0e73f)
val md_theme_light_onSecondaryContainer = Color(0xFF1e1c00)
val md_theme_light_tertiary = Color(0xFF9c4141)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffdad7)
val md_theme_light_onTertiaryContainer = Color(0xFF410006)
val md_theme_light_error = Color(0xFFB3261E)
val md_theme_light_errorContainer = Color(0xFFF9DEDC)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_background = Color(0xFFfbfdfd)
val md_theme_light_onBackground = Color(0xFF191c1d)
val md_theme_light_surface = Color(0xFFfbfdfd)
val md_theme_light_onSurface = Color(0xFF191c1d)
val md_theme_light_surfaceVariant = Color(0xFFE7E0EC)
val md_theme_light_onSurfaceVariant = Color(0xFF49454F)
val md_theme_light_outline = Color(0xFF79747E)
val md_theme_light_inverseOnSurface = Color(0xFFeff1f1)
val md_theme_light_inverseSurface = Color(0xFF2d3132)
val md_theme_light_inversePrimary = Color(0xFFffb865)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFffb865)
val md_theme_dark_onPrimary = Color(0xFF492900)
val md_theme_dark_primaryContainer = Color(0xFF683c00)
val md_theme_dark_onPrimaryContainer = Color(0xFFffdcb8)
val md_theme_dark_secondary = Color(0xFFd3cb1f)
val md_theme_dark_onSecondary = Color(0xFF353200)
val md_theme_dark_secondaryContainer = Color(0xFF4d4800)
val md_theme_dark_onSecondaryContainer = Color(0xFFf0e73f)
val md_theme_dark_tertiary = Color(0xFFffb3b0)
val md_theme_dark_onTertiary = Color(0xFF601318)
val md_theme_dark_tertiaryContainer = Color(0xFF7e2a2c)
val md_theme_dark_onTertiaryContainer = Color(0xFFffdad7)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_background = Color(0xFF191c1d)
val md_theme_dark_onBackground = Color(0xFFe0e3e3)
val md_theme_dark_surface = Color(0xFF191c1d)
val md_theme_dark_onSurface = Color(0xFFe0e3e3)
val md_theme_dark_surfaceVariant = Color(0xFF49454F)
val md_theme_dark_onSurfaceVariant = Color(0xFFCAC4D0)
val md_theme_dark_outline = Color(0xFF938F99)
val md_theme_dark_inverseOnSurface = Color(0xFF191c1d)
val md_theme_dark_inverseSurface = Color(0xFFe0e3e3)
val md_theme_dark_inversePrimary = Color(0xFF895100)
val md_theme_dark_shadow = Color(0xFF000000)

val seed = Color(0xFF6750A4)
val error = Color(0xFFB3261E)
